config/routes.rb
Rails.application.routes.draw do
  resources :recipes

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipe, only: [:show, :edit, :update, :destroy]
  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to @recipe, notice: 'Idea was successfully created.'
    else
      render action: 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @recipe.update_attributes(recipe_params)
      redirect_to @recipe, notice: 'Recipe was successfully updated.'
    else
      render action: 'edit'
    end
  end
  
  def destroy
    @recipe.destroy
    redirect_to action: 'new', notice: 'Idea was successfully deleted.'
  end

  private
    def recipe_params
      params.require(:recipe).permit(:title, :ingredients, :preparations, :image)
    end
  
    def find_recipe
      @recipe = Recipe.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecipeApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :ingredients %>
    <%= f.text_area :ingredients %>
  </div>

  <div>
    <%= f.label :preparations %>
    <%= f.text_area :preparations %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Rezept ändern</h1>

<%= render 'form' %>

app/views/recipes/index.html.erb
<h1>Alle Rezepte</h1>

<table>
  <tr>
    <th>Titel</th>
    <th>Preparations</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @recipes.each do |recipe| %>
  <tr>
    <td><%= recipe.title %></td>
    <td><%= recipe.preparations %></td>
    <td><%= link_to 'Show', recipe %></td>
    <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
    <td><%= link_to 'Destroy', recipe, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Neues Rezept', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>Neues Rezept anlegen</h1>

<%= render 'form' %>

app/views/recipes/show.html.erb
<h1><%= @recipe.title %></h1>
<p><%= @recipe.ingredients %></p>
<p><%= @recipe.preparations %></p>
<%= image_tag(@recipe.image, size: "300") %>
<p><%= link_to 'Destroy', @recipe, confirm: 'Are you sure?', method: :delete %></p>